In [126]:
import torch
import numpy as np

 ### Create Tensor 
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [127]:
t1 = torch.zeros(5, 3)
t1[0,2]= 10
t1[2,0]= 100
t1

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

In [128]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [129]:
# there are 24 elements in the tensor x
x.reshape(6,4).permute(1,0)

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# Logistic Loss and Autograd 

In [130]:
def f_composite(y,o):
  return torch.log(1+torch.exp(-y*o)) 


In [131]:
y = torch.tensor([-1., 1])      
o = np.linspace(-5, 5, num= 30)
o = torch.from_numpy(o) 

In [132]:
print(y)
print(o)

tensor([-1.,  1.])
tensor([-5.0000, -4.6552, -4.3103, -3.9655, -3.6207, -3.2759, -2.9310, -2.5862,
        -2.2414, -1.8966, -1.5517, -1.2069, -0.8621, -0.5172, -0.1724,  0.1724,
         0.5172,  0.8621,  1.2069,  1.5517,  1.8966,  2.2414,  2.5862,  2.9310,
         3.2759,  3.6207,  3.9655,  4.3103,  4.6552,  5.0000],
       dtype=torch.float64)


In [133]:
o.requires_grad_(True)

tensor([-5.0000, -4.6552, -4.3103, -3.9655, -3.6207, -3.2759, -2.9310, -2.5862,
        -2.2414, -1.8966, -1.5517, -1.2069, -0.8621, -0.5172, -0.1724,  0.1724,
         0.5172,  0.8621,  1.2069,  1.5517,  1.8966,  2.2414,  2.5862,  2.9310,
         3.2759,  3.6207,  3.9655,  4.3103,  4.6552,  5.0000],
       dtype=torch.float64, requires_grad=True)

In [134]:
y = y.reshape(2,1)

In [135]:
loss = f_composite(y,o)   #forward pass
loss.size()

torch.Size([2, 30])

In [136]:
loss

tensor([[0.0067, 0.0095, 0.0133, 0.0188, 0.0264, 0.0371, 0.0520, 0.0726, 0.1010,
         0.1398, 0.1922, 0.2617, 0.3523, 0.4676, 0.6107, 0.7831, 0.9848, 1.2143,
         1.4686, 1.7439, 2.0364, 2.3424, 2.6588, 2.9830, 3.3130, 3.6471, 3.9843,
         4.3237, 4.6646, 5.0067],
        [5.0067, 4.6646, 4.3237, 3.9843, 3.6471, 3.3130, 2.9830, 2.6588, 2.3424,
         2.0364, 1.7439, 1.4686, 1.2143, 0.9848, 0.7831, 0.6107, 0.4676, 0.3523,
         0.2617, 0.1922, 0.1398, 0.1010, 0.0726, 0.0520, 0.0371, 0.0264, 0.0188,
         0.0133, 0.0095, 0.0067]], dtype=torch.float64, grad_fn=<LogBackward>)

In [ ]:
#Install wandb and update it to the latest version
!pip install wandb --upgrade

In [139]:
# Import wandb
import wandb

# Login to W&B
wandb.login()

<IPython.core.display.Javascript object>

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


True

In [140]:
wandb.init(name = "HW Plots", project = 'HW3', id ='10_22_21')

wandb: Currently logged in as: suman17 (use `wandb login --relogin` to force relogin)


In [141]:
#o.grad.zero_()
loss = f_composite(y,o)   #forward pass
loss[1].sum().backward()
o_grad_y_pos = o.grad.clone().detach()

# after saving the gradients when y = 1, I reset the o.grad to 0. Then, find the
# gradients when y = -1
o.grad.zero_()
loss = f_composite(y,o)   #forward pass
loss[0].sum().backward()
o_grad_y_neg = o.grad

In [142]:
o_grad_y_pos

tensor([-0.9933, -0.9906, -0.9867, -0.9814, -0.9739, -0.9636, -0.9494, -0.9300,
        -0.9039, -0.8695, -0.8252, -0.7697, -0.7031, -0.6265, -0.5430, -0.4570,
        -0.3735, -0.2969, -0.2303, -0.1748, -0.1305, -0.0961, -0.0700, -0.0506,
        -0.0364, -0.0261, -0.0186, -0.0133, -0.0094, -0.0067],
       dtype=torch.float64)

In [143]:
o_grad_y_neg

tensor([0.0067, 0.0094, 0.0133, 0.0186, 0.0261, 0.0364, 0.0506, 0.0700, 0.0961,
        0.1305, 0.1748, 0.2303, 0.2969, 0.3735, 0.4570, 0.5430, 0.6265, 0.7031,
        0.7697, 0.8252, 0.8695, 0.9039, 0.9300, 0.9494, 0.9636, 0.9739, 0.9814,
        0.9867, 0.9906, 0.9933], dtype=torch.float64)

In [144]:
# Importing matplotlib library for visualizing 
# loss values for y over the range of o

import matplotlib.pyplot as plt
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
fig.suptitle('Loss Plots')

# We will create a scatter plot between feature and labels
ax1.scatter(o.detach().numpy(), loss[0].detach().numpy(),s = 1)
ax1.set(xlabel='O')
ax1.set(ylabel='loss(y = -1)')
ax2.scatter(o.detach().numpy(), loss[1].detach().numpy(), s = 1)
ax2.set(xlabel='O')
ax2.set(ylabel='loss(y = +1)')

wandb.log({"Loss Plots ": plt})

In [145]:
# Plot the loss gradient w.r.t o using autograd
# import matplotlib.pyplot as plt
fig, (a1, a2) = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
fig.suptitle('Gradient Plots')

# We will create a scatter plot between feature and labels
a1.scatter(o.detach().numpy(), o_grad_y_neg,s = 1)
a1.set(xlabel='O')
a1.set(ylabel='loss gradient wrt o when (y = -1)')
a2.scatter(o.detach().numpy(), o_grad_y_pos, s = 1)
a2.set(xlabel='O')
a2.set(ylabel='loss gradient wrt o when (y = +1)')

wandb.log({"Gradient Plot ": plt})

In [146]:
wandb.finish()

Both the Plots have been logged to wandb.

# Regression with Autograd 

1. Quadratic model where $\mathrm{y} = b + w_1 \cdot \mathrm{x} + w_2 \cdot \mathrm{x}^2$.
1. Linear model where $\mathrm{y} = b + w_1 \cdot \mathrm{x}$.
1. Linear model with no bias  where $\mathrm{y} = w_1 \cdot \mathrm{x}$.

In [147]:
x = torch.tensor([1.5420291, 1.8935232, 2.1603365, 2.5381863, 2.893443, \
                    3.838855, 3.925425, 4.2233696, 4.235571, 4.273397, \
                    4.9332876, 6.4704757, 6.517571, 6.87826, 7.0009003, \
                    7.035741, 7.278681, 7.7561755, 9.121138, 9.728281])
y = torch.tensor([63.802246, 80.036026, 91.4903, 108.28776, 122.781975, \
                    161.36314, 166.50816, 176.16772, 180.29395, 179.09758, \
                    206.21027, 272.71857, 272.24033, 289.54745, 293.8488, \
                    295.2281, 306.62274, 327.93243, 383.16296, 408.65967])

In [148]:
print(x.shape)

torch.Size([20])


Quadratic Model:

In [149]:
def reg_quadratic(x, w1, w2, b):
  return  b+ (x*w1) + ((x**2)*w2)

In [150]:
# Loss Function: Mean squared error

def mse_loss(ypred, y):
  error = ypred - y  #make them the same shape
  mse = sum(error**2)/len(y)   #square the errors and divide by length of y
  return mse


In [151]:
# optimisation of weight
# weight update step
def sgd(params, lr, batch_size):
  with torch.no_grad():
    for param in params:
        param.data -= lr * param.grad    
        param.grad.zero_()

In [152]:
import random

In [153]:
def read_data(batch_size, features, target):

  """
  Function to access data in mini batches. 
  Input parameters: batch size, features, labels. 
  Output: iterator for minibatch data
  """
  
  # Number of examples in the datasets
  num = len(features)
  
  # Creating a list of indices from 0 to number of examples in the dataset
  indices = list(range(num)) 
  
  # The examples are read at random, in no particular order
  random.shuffle(indices)
  
  # Return the features and labels of the minibatch
  for i in range(0, num, batch_size):
      batch_indices = torch.tensor(indices[i:min(i + batch_size, num)])
      yield features[batch_indices], target[batch_indices]

In [160]:
# Create a tensor weights with values from normal distribution
torch.manual_seed(0)
w1= torch.normal(0, 0.01, size= (1,), requires_grad =True)
w2= torch.normal(0, 0.01, size= (1,), requires_grad =True)

# Create a tensor for bias
b = torch.zeros(1, requires_grad=True)

# Set the values for learning rate and number of epochs
lr = 0.0005
epochs = 25
batch_size = 5

# Iterate over the whole dataset
for epoch in range(epochs):
  
  for x1,y1 in read_data(batch_size,x,y):  #x1, y1 is 
    # step 1 :forward pass - compute predictions
    ypred = reg_quadratic(x1, w1, w2, b)
    #print(ypred)
    # step 2: Calculate minibatch loss
    batch_loss = mse_loss(ypred, y1)

    # step 3: Compute gradient on loss with respect to weights and bias
    batch_loss.backward()

    # step 4: Update parameters using their gradient using optimization algorithm
    sgd([w1,w2,b], lr, batch_size)  

    
    # Calculate and print loss for the complete epoch
  train_l = mse_loss(reg_quadratic(x, w1,w2, b), y)

  print(f'epoch {epoch + 1}, loss {train_l.item():f}')


epoch 1, loss 10643.785156
epoch 2, loss 10084.217773
epoch 3, loss 4847.779297
epoch 4, loss 4525.648438
epoch 5, loss 7139.485840
epoch 6, loss 18050.443359
epoch 7, loss 6022.963867
epoch 8, loss 10053.482422
epoch 9, loss 3532.951660
epoch 10, loss 95694.953125
epoch 11, loss 8414.424805
epoch 12, loss 4988.118164
epoch 13, loss 3197.596191
epoch 14, loss 4083.737549
epoch 15, loss 3047.181152
epoch 16, loss 3320.827393
epoch 17, loss 19439.253906
epoch 18, loss 15208.956055
epoch 19, loss 4350.045898
epoch 20, loss 37483.835938
epoch 21, loss 5084.118164
epoch 22, loss 79425.390625
epoch 23, loss 67514.125000
epoch 24, loss 4030.705566
epoch 25, loss 11358.676758


At first when a learning rate of 0.001 was used, the losses reached infinity over the epochs. When the learning rate was reduced further to 0.0005, the losses are reducing. However, we can see that this model is not doing well in predicting target values. 

In [155]:
train_l.type()

'torch.FloatTensor'

Linear Model with bias:

In [156]:
def reg_linear_bias(x,w,b):
  return b+x*w

In [161]:
# Set the values for learning rate and number of epochs
torch.manual_seed(0)
w1= torch.normal(0, 0.01, size= (1,), requires_grad =True)
b = torch.zeros(1, requires_grad=True)

lr = 0.001
epochs = 25
batch_size = 5

# Iterate over the whole dataset
for epoch in range(epochs):
  
  for x1,y1 in read_data(batch_size,x,y):
    # step 1 :forward pass - compute predictions
    ypred = reg_linear_bias(x1, w1, b)
    #print(ypred)
    # step 2: Calculate minibatch loss
    batch_loss = mse_loss(ypred, y1)

    # step 3: Compute gradient on loss with respect to weights and bias
    batch_loss.backward()

    # step 4: Update parameters using their gradient using optimization algorithm
    sgd([w1,b], lr, batch_size)  

    
    # Calculate and print loss for the complete epoch with updated w1 and b.
  train_l = mse_loss(reg_linear_bias(x, w1, b), y)

  print(f'epoch {epoch + 1}, loss {train_l.item():f}')


epoch 1, loss 33145.660156
epoch 2, loss 18978.937500
epoch 3, loss 10878.622070
epoch 4, loss 6210.262695
epoch 5, loss 3560.702637
epoch 6, loss 2036.272827
epoch 7, loss 1168.725464
epoch 8, loss 670.236572
epoch 9, loss 386.217468
epoch 10, loss 223.898102
epoch 11, loss 130.912567
epoch 12, loss 77.608215
epoch 13, loss 47.236809
epoch 14, loss 30.099461
epoch 15, loss 20.095436
epoch 16, loss 14.554273
epoch 17, loss 11.396231
epoch 18, loss 9.493280
epoch 19, loss 8.383291
epoch 20, loss 7.793767
epoch 21, loss 7.445793
epoch 22, loss 7.236188
epoch 23, loss 7.108051
epoch 24, loss 7.028387
epoch 25, loss 6.980836


The losses have reduced significantly with the Linear Model. This model is doing so much better than the previous model. 

Linear Model Without Bias:

In [158]:
def reg_linear(x,w):
  return w1* x

In [162]:
# Set the values for learning rate and number of epochs
lr = 0.001
epochs = 25
batch_size = 5
torch.manual_seed(0)
w1= torch.normal(0, 0.01, size= (1,), requires_grad =True)

# Iterate over the whole dataset
for epoch in range(epochs):
  
  for x1,y1 in read_data(batch_size,x,y):
    # step 1 :forward pass - compute predictions
    ypred = reg_linear(x1, w1)
    #print(ypred)
    # step 2: Calculate minibatch loss
    batch_loss = mse_loss(ypred, y1)

    # step 3: Compute gradient on loss with respect to weights and bias
    batch_loss.backward()

    # step 4: Update parameters using their gradient using optimization algorithm
    sgd([w1,b], lr, batch_size)  

    
    # Calculate and print loss for the complete epoch with updated w1 and b.
  train_l = mse_loss(reg_linear(x, w1), y)
        
  print(f'epoch {epoch + 1}, loss {train_l.item():f}')

epoch 1, loss 33648.136719
epoch 2, loss 19553.312500
epoch 3, loss 11312.330078
epoch 4, loss 6559.813477
epoch 5, loss 3806.496094
epoch 6, loss 2205.184570
epoch 7, loss 1279.447754
epoch 8, loss 744.277710
epoch 9, loss 433.173248
epoch 10, loss 252.265259
epoch 11, loss 146.941925
epoch 12, loss 85.685555
epoch 13, loss 50.333138
epoch 14, loss 29.809921
epoch 15, loss 17.784864
epoch 16, loss 10.868855
epoch 17, loss 6.807874
epoch 18, loss 4.452893
epoch 19, loss 3.088621
epoch 20, loss 2.303412
epoch 21, loss 1.847614
epoch 22, loss 1.586941
epoch 23, loss 1.435534
epoch 24, loss 1.345485
epoch 25, loss 1.292068


The Linear Model without Bias is doing very well at predicting the target values. This model is the best model among all three.

# Topic Model 

data from stackexchnage Question/Answer forum. [link](https://drive.google.com/file/d/1-36loS5uyn6wGcb9FO11FTku8-r9u01M/view?usp=sharing).


In [1]:
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
basepath= '/content/drive/MyDrive/Colab_Notebooks/topic_no_tag.csv'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data = Path(basepath)

In [5]:
file = pd.read_csv(data)

In [6]:
file

Unnamed: 0                                               Body
0         104835  <p>Is there a simple way to place a detail dis...
1         146243  <p>I followed Hello World tutorial exactly.  E...
2          28023  <p>Trying to validate some Javascript in JsHin...
3          44485  <p>I'm trying to make a data bound column invi...
4         107818  <p>The home screen of my Android application h...
...          ...                                                ...
4996      143077  <p>I have a list of inflated rows that have tw...
4997      127644  <p>I have the following code and want to write...
4998      203361  <p><a href="http://jsfiddle.net/mjmitche/gq6En...
4999       15319  <p>The following code produces a list with no ...
5000      210938  <p>To save an image I use the following code: ...

[5001 rows x 2 columns]

In [7]:
#remove any html tags from Reviews
from bs4 import BeautifulSoup
import re

def basic_clean(text):
        if (bool(BeautifulSoup(text, "html.parser").find())==True):         
          soup = BeautifulSoup(text, "html.parser")
          text = soup.get_text()
        else:
            pass
        return re.sub(r'[\n\r]',' ', text) 

In [8]:
file['Body'] = [basic_clean(question)  for question in file['Body']]
file.head()

Unnamed: 0                                               Body
0      104835  Is there a simple way to place a detail disclo...
1      146243  I followed Hello World tutorial exactly.  Emul...
2       28023  Trying to validate some Javascript in JsHint, ...
3       44485  I'm trying to make a data bound column invisib...
4      107818  The home screen of my Android application has ...

In [9]:
tfidf = TfidfVectorizer(max_df= 0.95, min_df= 2, stop_words= 'english')
file_vectors = tfidf.fit_transform(file['Body']).todense()
file_vectors.shape   #documents, vocab

(5001, 9431)

In [12]:
vocab = np.array(tfidf.get_feature_names())
vocab.shape

(9431,)

In [13]:
from sklearn.model_selection import train_test_split
X_train= file_vectors
# X_train, X_test = train_test_split(X, random_state=0)
print(f'X_train: {X_train.shape}')
# print(f'X_test: {X_test.shape}')

X_train: (5001, 9431)


In [14]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import GridSearchCV

model = LatentDirichletAllocation(random_state= 0)

In [59]:
np.set_printoptions(threshold=np.inf)
X_train[2][[(X_train[[2]] != 0)]]

/usr/local/lib/python3.7/dist-packages/numpy/matrixlib/defmatrix.py:193: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = N.ndarray.__getitem__(self, index)


matrix([[0.23358582, 0.19243961, 0.32835185, 0.12656922, 0.35037426,
         0.12821056, 0.23358582, 0.20974931, 0.18911618, 0.1464072 ,
         0.34956167, 0.14015531, 0.11804456, 0.28560137, 0.11084306,
         0.25127713, 0.12787706, 0.23998626, 0.32078174]])

In [16]:
grid_param= {'n_components': [3, 5, 10], 'learning_method': ['batch', 'online']}

grid_lda = GridSearchCV(model, param_grid= grid_param, cv= 5)

In [17]:
grid_lda.fit(X_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LatentDirichletAllocation(batch_size=128,
                                                 doc_topic_prior=None,
                                                 evaluate_every=-1,
                                                 learning_decay=0.7,
                                                 learning_method='batch',
                                                 learning_offset=10.0,
                                                 max_doc_update_iter=100,
                                                 max_iter=10,
                                                 mean_change_tol=0.001,
                                                 n_components=10, n_jobs=None,
                                                 perp_tol=0.1, random_state=0,
                                                 topic_word_prior=None,
                                                 total_samples=1000000.0,
                                  

In [60]:
# Best Model
best_lda_model = grid_lda.best_estimator_

# Model Parameters
print("Best Model's Params: ", grid_lda.best_params_)

# Log Likelihood Score
print("Best Log Likelihood Score: ", grid_lda.best_score_)

Best Model's Params:  {'learning_method': 'online', 'n_components': 3}
Best Log Likelihood Score:  -45184.615496782004


In [124]:
n=50
for index,topic in enumerate(best_lda_model.components_):
    print(f'THE TOP {n} WORDS FOR TOPIC {index}\n{[vocab[i] for i in topic.argsort()[-n:]]}\n')  

THE TOP 50 WORDS FOR TOPIC 0
['q2', 'resolutions', 'gety', 'location1', 'stderr', 'treeview', 'ontouchevent', 'mv', 'cos', 'getheight', 'soapobject', 'imag', 'annotations', 'd3', 'arg2', 'prodid', 'arg1', 'func1', 'listdir', 'defaultdict', 'prog', 'rect', 'myresponse', '12345', 'responselist', 'sum1', 'defaultbutton', 'getx', 'lat', 'hotmail', 'd2', 'namelist', 'd1', 'getwidth', 'pipe', 'foobar', 'axis', 'paint', 'plot', 'rotation', 'distance', 'longitude', 'latitude', 'locationmanager', 'stdout', 'dataset', 'motionevent', 'matrix', 'canvas', 'arr']

THE TOP 50 WORDS FOR TOPIC 1
['category', 'orientation', 'toast', '03', 'self', 'app', 'tableview', 'alloc', 'xml', 'contacts', 'override', '07', 'permission', 'id', '11', '02', 'datetime', 'layoutparams', '2011', '05', 'super', 'nsstring', 'androidruntime', '12', 'day', '04', 'java', 'fill_parent', 'activities', 'layout', 'bundle', 'linearlayout', 'apk', 'calendar', 'savedinstancestate', 'wrap_content', 'layout_width', 'layout_height', 't

As per Grid Search results the optimum number of topics is 3. Upon printing the top 50 words for each topic, we can see that:<br>
Topic 0: Topic 0 consists of words belonging to various miscellaneous topics.<br>
Topic 1: Most of words under Topic 1 are related to either Android or iOS, i.e., Mobile related.  <br>
Topic 2: This seems to be mixed a bit but there is a majority of Javascript/Web related words. 

In [68]:
topic_train= best_lda_model.transform(X_train)

In [74]:
topic_train    #rows= words, cols= topics 

array([[0.0594815 , 0.19799767, 0.74252083],
       [0.05318331, 0.54650883, 0.40030786],
       [0.06821757, 0.06701423, 0.86476821],
       ...,
       [0.07163605, 0.07165024, 0.85671371],
       [0.06718086, 0.06709897, 0.86572017],
       [0.05502533, 0.0550237 , 0.88995097]])

In [163]:
import random

Now I am going to check the results of LDA model with 4 topics to see if it yields a better result.

In [75]:
# LDA model with 4 components
model_lda_2= LatentDirichletAllocation(learning_method= 'online', 
                                       n_components= 4, random_state= 5)
model_lda_2.fit(X_train)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='online', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=4, n_jobs=None,
                          perp_tol=0.1, random_state=5, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [123]:
n=50
for index,topic in enumerate(model_lda_2.components_):
    print(f'THE TOP {n} WORDS FOR TOPIC {index}
          \n{[vocab[i] for i in topic.argsort()[-n:]]}\n') 

THE TOP 50 WORDS FOR TOPIC 0
['set', 'com', 'void', 'just', 'example', 'click', 'input', 'does', 'app', 'possible', 'script', 'help', 'object', 'method', 'button', 'array', 'jquery', 'type', 'list', 'return', 'page', 'way', 'know', 'image', 'error', 'user', 'data', 'java', 'need', 'application', 'use', 'thanks', 'public', 'text', 'var', 'div', 'value', 'int', 'php', 'id', 'using', 'new', 'like', 'file', 'class', 'want', 'code', 'string', 'android', 'function']

THE TOP 50 WORDS FOR TOPIC 1
['mssql', 'gt', 'flv', 'myresponse', 'smtp', 'kant', 'addsubview', 'dist', 'mytable', 'discount', 'navigationbar', 'user_id', 'mysqli', 'cgrectmake', 'appstore', 'catalog', 'isa', 'defaultbutton', 'fraction', 'key1', 'key2', 'alloc', 'navigationcontroller', 'hotmail', 'connectionstring', 'uibutton', 'file1', 'session_start', 'file2', 'viewcontroller', 'col', 'lastname', 'firstname', 'die', 'table', 'role', 'uid', 'ds', 'dropdownlist', 'alarmmanager', 'mysql_error', 'dataset', 'th', 'yahoo', 'mysql_qu

Topic 0: This topic contains over 98% of the documents and is a mixed bag of different topics.(web, android, java etc)  <br>
Topic 1: We can see that the some words are related to iOS and some others related to tables and database. There is no clear distinction in a single topic.<br>
Topic 2: We see a mixture of iOS related words and date, location related words. No clear demarcation is observed.  <br>
Topic 3: The top words seem to be related to either lists or pages.

In [112]:
# I am checking the number of documents under Topic 0

topic_train_2= model_lda_2.transform(X_train)
X_train[topic_train_2[:,0] > 0.5].shape


(4913, 9431)

Upon checking the two LDA models with n_components being 3 and 4, we see that the First Model with n_components = 3 is giving a better result than the latter. Therefore, I am choosing the first LDA model 